include:
  - project: tools/pipeline-templates
    ref: master
    file: kubernetes/glue-k8s-deploy/v3/acceptance-union-deliver.yml

.deploy-defaults:
  variables:
    KAPP_NAMESPACE: zabbix-jr
    ZABBIX_IMAGE_TAG: "ubuntu-7.4.8"
    STORAGE_CLASS: "gp3-wait-retain-xfs-encrypted"
    SAML_SP_CRT_B64:
    SAML_SP_KEY_B64:
    ONPREM_ZABBIX_HOST: "nlmgmt032.bethel.jw.org"

deploy-acceptance:
  environment:
    name: acceptance/${CI_COMMIT_REF_SLUG}
    url: https://zabbix-jr-${CI_MERGE_REQUEST_IID}.o11n-acceptance.jw-cd-cicd-01.10aws.org
  variables:
    AWS: jw-cd-cicd-01
    CI_ENVIRONMENT_SLUG: acceptance
    HOST_NAME: zabbix-jr-${CI_MERGE_REQUEST_IID}.o11n-acceptance.jw-cd-cicd-01.10aws.org
    KUBECFG_VAULT_PATH: secret/systems/eks/o11n-eks-o11n-acceptance
    STORAGE_CLASS: "gp3-wait-delete-xfs-encrypted"
    CUSTOM_VAULT_PATHS: kv2/data/appsvc/azure-ad/apps/jw-cd-azure/${CI_PROJECT_PATH}-union

delete-acceptance:
  variables:
    AWS: jw-cd-cicd-01
    KUBECFG_VAULT_PATH: secret/systems/eks/o11n-eks-o11n-acceptance
    CUSTOM_VAULT_PATHS: kv2/data/appsvc/azure-ad/apps/jw-cd-azure/${CI_PROJECT_PATH}-union

deploy-union:
  variables:
    AWS: jw-cd-orchestration-prd
    CI_ENVIRONMENT_SLUG: union
    HOST_NAME: zabbix-jr.o11n-union.jw-cd-orchestration-prd.10aws.org
    KUBECFG_VAULT_PATH: secret/systems/eks/o11n-eks-o11n-union
    CUSTOM_VAULT_PATHS: kv2/data/appsvc/azure-ad/apps/jw-cd-azure/${CI_PROJECT_PATH}-union

deploy-deliver:
  variables:
    CI_ENVIRONMENT_SLUG: deliver
    DISABLED: "true"
