include:
  - project: tools/pipeline-templates
    ref: master
    file: kubernetes/glue-k8s-deploy/v3/acceptance-union-deliver.yml

deploy-acceptance:
  environment:
    url: https://zabbix-jr.o11n-acceptance.jw-cd-cicd-01.10aws.org/acceptance/${CI_COMMIT_REF_SLUG}/index.html
  variables:
    AWS: jw-cd-cicd-01
    KAPP_NAMESPACE: zabbix-jr
    KUBECFG_VAULT_PATH: secret/systems/eks/o11n-eks-o11n-acceptance

delete-acceptance:
  variables:
    AWS: jw-cd-cicd-01
    KAPP_NAMESPACE: zabbix-jr
    KUBECFG_VAULT_PATH: secret/systems/eks/o11n-eks-o11n-acceptance

deploy-union:
  variables:
    DISABLED: "true"

deploy-deliver:
  variables:
    DISABLED: "true"

