services:
  glue-k8s-deploy:
    image: docker.packages.bethelservice.org/glue-k8s-deploy:compat
    platform: linux/amd64
    user: root
    privileged: true
    network_mode: bridge
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    volumes:
      - ./:/src
    command: glue-k8s-deploy
    environment:
      ARTIFACTORY_USERNAME:
      ARTIFACTORY_ACCESS_TOKEN:
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      CI_PROJECT_PATH: zabbix/zabbix-jr
      CI_COMMIT_REF_SLUG: lab1-$USER
      CI_ENVIRONMENT_SLUG: dev
      KAPP_NAMESPACE: "$USER"
      GLUE_CMD: ${GLUE_CMD:-deploy}
      WORKING_DIR: "/src"
      DEPLOYMENT_FOLDER: "/src/deployment/"
      KUBECFG_VAULT_PATH: "secret/systems/eks/o11n-eks-o11n-dev"
      CUSTOM_VAULT_PATHS: kv2/data/appsvc/azure-ad/apps/jw-cd-azure/${CI_PROJECT_PATH}-union
      SAML_SP_CRT_B64:
      SAML_SP_KEY_B64:
      BUILD_MODE: "none"
      SKIP_MIRROR_IMAGES: "true"
      STORAGE_CLASS: "gp3-wait-delete-xfs-encrypted"
      ZABBIX_IMAGE_TAG: "ubuntu-7.4.8"
      ZABBIX_SERVER_DEBUGLEVEL: "5"
      ONPREM_ZABBIX_HOST: ${ONPREM_ZABBIX_HOST:-}
      HOST_NAME: zabbix-$USER.o11n-dev.jw-cd-lab-1.10aws.org
      VAULT_ADDR: https://vault.o11n.jw-cd-gitlab.10aws.org
      VAULT_ROLE:
      VAULT_TOKEN:
