---
# Source: zabbix/templates/deployment-zabbix-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-zabbix-web
  namespace: avacameron
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: web
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix
      app.kubernetes.io/instance: zabbix
      app.kubernetes.io/component: web
  template:
    metadata:
      annotations:
      labels:
        helm.sh/chart: zabbix-7.0.12
        app.kubernetes.io/name: zabbix
        app.kubernetes.io/instance: zabbix
        app.kubernetes.io/version: "7.0.16"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: zabbix
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: zabbix-zabbix-web
      containers:
      - name: zabbix-web
        resources:
          {}
        securityContext:
          {}
        image: "zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0.16"
        imagePullPolicy: IfNotPresent
        env:
          
          
          - name: DB_SERVER_HOST
            value: zabbix-postgresql
          - name: DB_SERVER_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-db-access
                key: user
                optional: true
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-db-access
                key: password
          - name: POSTGRES_DB
            value: "zabbix"
        ports:
          - name: zabbix-web
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /ping
            port: zabbix-web
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /ping
            port: zabbix-web
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      imagePullSecrets:
      volumes:
