---
# Source: zabbix/templates/secret-db-access.yaml
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-access
  namespace: zabbix-jr
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  host: "emFiYml4LXBvc3RncmVzcWw="
  port: "NTQzMg=="
  dbname: "emFiYml4"
  user: "emFiYml4"
  password: "emFiYml4"
