---
# Source: zabbix/templates/extra-manifests.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 'zabbix'
  namespace: 'zabbix-jr'
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  verbs:
  - get
  - list
---
# Source: zabbix/templates/extra-manifests.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'zabbix'
  namespace: 'zabbix-jr'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'zabbix'
subjects:
- kind: ServiceAccount
  name: 'zabbix'
  namespace: 'zabbix-jr'
---
# Source: zabbix/templates/extra-manifests.yaml
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  annotations:
    kubernetes.io/ingress.class: kube-alb
  name: zabbix-route-group
  namespace: 'zabbix-jr'
spec:
  backends:
  - name: zabbix-web
    serviceName: zabbix-zabbix-web
    servicePort: 80
    type: service
  hosts:
  - zabbix-jr.o11n-acceptance.jw-cd-cicd-01.10aws.org
  routes:
  - backends:
    - backendName: zabbix-web
    pathSubtree: /
