---
# Source: zabbix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zabbix-zabbix-server
  namespace: zabbix-jr
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - port: 443
      name: zabbix-server
      targetPort: 10051
      protocol: TCP
    - port: 10052
      name: zabbix-jmx
      targetPort: 10052
      protocol: TCP
  selector:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/component: server
---
# Source: zabbix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zabbix-zabbix-web
  namespace: zabbix-jr
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 80
      name: zabbix-web
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/component: web
---
# Source: zabbix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zabbix-zabbix-webservice
  namespace: zabbix-jr
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: webservice
spec:
  type: ClusterIP
  ports:
    - port: 10053
      name: webservice
      targetPort: 10053
      protocol: TCP
  selector:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/component: webservice
---
# Source: zabbix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgresql
  namespace: zabbix-jr
  labels:
    helm.sh/chart: zabbix-7.0.12
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/version: "7.0.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: db
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
    app.kubernetes.io/component: postgresql
